### PR TITLE
HTML API: Introduce HTML templating

### PR DESCRIPTION
**Pull request by dmsnell**
Trac ticket: Core-60229

🚧👷‍♂️🏗️ This feature is currently being proposed for the *WordPress 6.6* release cycle, being pushed back from 6.5 to allow for more time to let the design work proceed.

**To be recreated** in the WordPress repo once WordPress/WordPress-develop#5683 merges.

## Todo

 - [ ] embed replacement inside the Tag Processor
 - [ ] don't allow replacement of escaped funky comment syntax (currently occurs inside attribute value based on how this is built at the moment)
 - [ ] figure out what rules need to apply for nested HTML
 - [ ] figure out how to differentiate nested HTML without requiring sigils or other extra syntax

## Description

Currently only renders text data:

 - does not render nested HTML (escapes everything)
 - does not escape URLs differently than other attributes
 - relies on `esc_attr()` and `esc_html()` which today are the same thing in WordPress, but which could be greatly expanded to improve the overall escaping situation

```php
echo WP_HTML_Template::render(
	<<<HTML
<a href="</%url>">
	<img src="</%url>">
	</%url>
</a>
HTML,
	array( 'url' => 'https://s.wp.com/i/atat.png?w=640&h=480&alt="atat>atst"' ),
);
```

outputs

```html
<a href="https://s.wp.com/i/atat.png?w=640&amp;h=480&amp;alt=&quot;atat&gt;atst&quot;">
<img src="https://s.wp.com/i/atat.png?w=640&amp;h=480&amp;alt=&quot;atat&gt;atst&quot;">
https://s.wp.com/i/atat.png?w=640&amp;h=480&amp;alt=&quot;atat&gt;atst&quot;
</a>
```

This proposed templating syntax uses closing tags containing invalid tag names, so-called "funky comments," as placeholders, because they are converted to HTML comments in the DOM and because there is near universal existing support for them in all browsers, and because the syntax cannot be nested. The % at the front indicates that the value for the placeholder should come from the args array with a key named according to what follows the %.

### CODE REVIEW

**Comment by dmsnell** [comment]
cc: @westonruter @ockham

**Comment by westonruter** [comment]
> * funky comment syntax

What is the reasoning behind the current syntax?

**Comment by dmsnell** [comment]
Sorry @westonruter - the reasoning was in the Trac ticket, but I've copied it here.

I also wrote about it in the [HTML API Progress Report](https://make.wordpress.org/core/2023/08/19/progress-report-html-api/#templating) a while back. The idea is that this happens to be a convenient syntax that checks off basically everything I've been looking for in order to [replace dynamic content](https://github.com/WordPress/gutenberg/discussions/39831#discussioncomment-7516498) - shortcodes 2.0.

In short (very short):
 - funky comments cannot be nested, by construction
 - once inside a funky comment, all bytes are allowed until the first ASCII `>`
 - the first symbol provides a very convenient sigil form to differentiate multiple kinds of bits of content: a placeholder, a shortcode, a translation, etc…
 - these are pure HTML and not a new superset syntax of HTML, meaning that when editing in an HTML editor they should stand out properly and not break the flow.
 - being existing HTML syntax, they cannot break syntax boundaries and cause further parsing problems down the line
 - they are concise and easily hand-written

**Comment by dmsnell** [comment]
Closing to recreate in WordPress/wordpress-develop

**Comment by dmsnell** [comment]
Replaced by https://github.com/WordPress/wordpress-develop/pull/5949

**Pull request closed without merging**
